import Foundation

/// The compatibility dashboard: per-construct, tier-aware conformance results
/// aggregated from a renderer run. Grouped by the matrix construct identifier
/// and tier (not raw upstream `section`). Markdown2-extension constructs are not
/// represented in the corpus and so are excluded from the upstream pass-rate;
/// they are listed separately and covered by their local tests.
struct ConformanceDashboard: Codable, Sendable {
    struct Overall: Codable, Sendable {
        let referenceMatch: Int
        let total: Int
        let passRatePercent: Int
    }

    struct Construct: Codable, Sendable {
        let id: String
        let tier: String
        let passed: Int
        let total: Int
        let passRatePercent: Int
    }

    struct Extension: Codable, Sendable {
        let id: String
        let tier: String
        let localTests: [String]
    }

    struct Failure: Codable, Sendable {
        let id: String
        let construct: String
        let section: String
        let relationship: String
        let markdown: String
        let reference: String
        let rendered: String
    }

    let overall: Overall
    let constructs: [Construct]
    let extensions: [Extension]
    let failures: [Failure]

    static let markdownPath = Fixtures.url("Conformance/dashboard.md")
    static let jsonPath = Fixtures.url("Conformance/dashboard.json")

    static func build(results: [ConformanceResult], matrix: CompatibilityMatrix) -> ConformanceDashboard {
        let byConstruct = Dictionary(grouping: results, by: \.constructID)

        // Per-construct rows in matrix order, corpus-backed constructs only.
        var constructs: [Construct] = []
        for entry in matrix.entries where !entry.sections.isEmpty {
            let group = byConstruct[entry.id] ?? []
            let total = group.count
            let passed = group.filter(\.matches).count
            constructs.append(Construct(
                id: entry.id,
                tier: entry.tier,
                passed: passed,
                total: total,
                passRatePercent: percent(passed, of: total)
            ))
        }

        let extensions = matrix.entries
            .filter { $0.origin == CompatibilityMatrix.extensionOrigin }
            .map { Extension(id: $0.id, tier: $0.tier, localTests: $0.localTests ?? []) }

        let matchTotal = results.filter(\.matches).count
        let overall = Overall(
            referenceMatch: matchTotal,
            total: results.count,
            passRatePercent: percent(matchTotal, of: results.count)
        )

        let failures = results.filter { !$0.matches }.map { result in
            Failure(
                id: result.entry.id,
                construct: result.constructID,
                section: result.entry.section,
                relationship: result.relationship.rawValue,
                markdown: result.entry.example.markdown,
                reference: result.reference,
                rendered: result.rendered
            )
        }

        return ConformanceDashboard(
            overall: overall,
            constructs: constructs,
            extensions: extensions,
            failures: failures
        )
    }

    private static func percent(_ value: Int, of total: Int) -> Int {
        guard total > 0 else { return 0 }
        return Int((Double(value) / Double(total) * 100).rounded())
    }

    func summaryLine() -> String {
        "Markdown compatibility: \(overall.referenceMatch)/\(overall.total) "
            + "upstream reference matches (\(overall.passRatePercent)%) across \(constructs.count) constructs"
    }

    func markdownReport() -> String {
        var lines: [String] = []
        lines.append("# Markdown compatibility dashboard")
        lines.append("")
        lines.append("Generated by `MarkdownConformanceDashboardTests`. Upstream conformance is "
            + "measured against the vendored CommonMark/GFM corpus under documented normalisation; "
            + "it is a tracked number, not a 100% target. Several divergences are intentional "
            + "product choices (see the support tier and the matrix).")
        lines.append("")
        lines.append("**Overall upstream reference match: \(overall.referenceMatch)/\(overall.total) "
            + "(\(overall.passRatePercent)%)**")
        lines.append("")
        lines.append("| Construct | Tier | Match | Total | Rate |")
        lines.append("| --- | --- | ---: | ---: | ---: |")
        for c in constructs {
            lines.append("| \(c.id) | \(c.tier) | \(c.passed) | \(c.total) | \(c.passRatePercent)% |")
        }
        lines.append("")
        lines.append("## Markdown2 extensions (not in the upstream pass-rate)")
        lines.append("")
        lines.append("| Construct | Tier | Local tests |")
        lines.append("| --- | --- | --- |")
        for e in extensions {
            lines.append("| \(e.id) | \(e.tier) | \(e.localTests.joined(separator: ", ")) |")
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    func write() throws {
        try markdownReport().data(using: .utf8)?.write(to: Self.markdownPath)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        try encoder.encode(self).write(to: Self.jsonPath)
    }
}
